name: Validate the composer.json file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-composer-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate composer.json
        run: composer validate
